from abc import ABC, abstractmethod
import numpy as np

class RecognizerBase(ABC):
    @abstractmethod
    def train(self, images, labels): ...
    @abstractmethod
    def predict(self, img) -> tuple[int, float]: ...
    @abstractmethod
    def save(self, path: str): ...
    @abstractmethod
    def load(self, path: str): ...
